AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-app

  Root stack for managing orders-app resources

Parameters:
  PruebaFunction:
    Type: String
    Description: PruebaFunction Function ARN

  CognitoUserPool:
    Type: String
    Description: CreateUser Function ARN


Resources:
  TransportAppAdminApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api-gateway
      StageName: Prod
#      MethodSettings:
#        - HttpMethod: "*"
#          LoggingLevel: INFO
#          ResourcePath: "/*"
#          MetricsEnabled: true
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
#        MaxAge: "'600'"
      # Auth:
      #   DefaultAuthorizer: CognitoAuthorizer
      #   Authorizers:
      #     CognitoAuthorizer:
      #       UserPoolArn: !Ref CognitoUserPool
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: definition/openapi.yaml

  ApiGwExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ApiGwExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
#              - Action: sqs:SendMessage
#                Effect: Allow
#                Resource:
#                  - Ref: OrderQueueArn
              - Action: lambda:*
                Effect: Allow
                Resource:
                  - Ref: PruebaFunction

Outputs:
  TransportAppApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for transport App admin"
    Value: !Sub "https://${TransportAppAdminApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
