version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "base-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jq1nr4tbelwj"
s3_prefix = "base-app"
region = "us-east-1"
profile = "transportApp"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
image_repositories = []
