version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "babygift-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dh7ywbn8gsfr"
s3_prefix = "babygift-app"
region = "us-east-1"
profile = "cp"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
image_repositories = []
