AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Base para nuevas aplicaciones AWS SaaS

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: nodejs16.x
  Api:
    TracingEnabled: True

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml

  ProductsModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/products-module/template.yaml
      Parameters:
        # PYTHON LIBRARY
        LayerLibsPython: !Ref LayerLibsPython
        # MAIN STACKNAME
        MainStackName: !Sub ${AWS::StackName}
        # MAIN TABLE BABYGIFT
        MainTableBabyGift: !Ref MainTableBabyGift
    DependsOn: Cognito

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-gateway/template.yaml
      Parameters:
        # COGNITO ARN
        CognitoUserPool: !GetAtt Cognito.Outputs.UserPoolARN
        # CATEGORIES FUNCTIONS
        CreateCategory: !GetAtt ProductsModule.Outputs.CreateCategory
        ReadCategory: !GetAtt ProductsModule.Outputs.ReadCategory
        UpdateCategory: !GetAtt ProductsModule.Outputs.UpdateCategory
        DeleteCategory: !GetAtt ProductsModule.Outputs.DeleteCategory
        # PRODUCTS FUNCTIONS
        GetProducts: !GetAtt ProductsModule.Outputs.GetProducts
        CreateProduct: !GetAtt ProductsModule.Outputs.CreateProduct
        ReadProduct: !GetAtt ProductsModule.Outputs.ReadProduct
        UpdateProduct: !GetAtt ProductsModule.Outputs.UpdateProduct
        DeleteProduct: !GetAtt ProductsModule.Outputs.DeleteProduct
        # MAIN STACKNAME
        MainStackName: !Sub ${AWS::StackName}
    DependsOn:
      - Cognito
      - ProductsModule

  LayerLibsPython:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-layer-lib-python
      Description: Librerías para funciones lambda de Python.
      ContentUri: src/shared/libs/.
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.9
    DependsOn: Cognito

  MainTableBabyGift:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-MainTableBabyGift
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "Data"
          AttributeType: "S"
        - AttributeName: "CategoryId"
          AttributeType: "S"
        - AttributeName: "SupplierId"
          AttributeType: "S"
        - AttributeName: "CustomerId"
          AttributeType: "S"
        - AttributeName: "StatusOrder"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: HASH
        - AttributeName: "SK"
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: 'GSI_1'
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "Data"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: 'GSI_2'
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "CategoryId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: 'GSI_3'
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "SupplierId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: 'GSI_4'
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "CustomerId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: 'GSI_5'
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "StatusOrder"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
    DependsOn: Cognito
