AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Base para nuevas aplicaciones AWS SaaS

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: nodejs16.x
  Api:
    TracingEnabled: True

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml

  ProductsModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/products/template.yaml
      Parameters:
        # LIBRERIA PYTHON
        LayerLibsPython: !Ref LayerLibsPython
    DependsOn: Cognito

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-gateway/template.yaml
      Parameters:
        # COGNITO ARN
        CognitoUserPool: !GetAtt Cognito.Outputs.UserPoolARN
        # CATEGORIES FUNCTIONS
        GetCategories: !GetAtt ProductsModule.Outputs.GetCategories
        CreateCategory: !GetAtt ProductsModule.Outputs.CreateCategory
        ReadCategory: !GetAtt ProductsModule.Outputs.ReadCategory
        UpdateCategory: !GetAtt ProductsModule.Outputs.UpdateCategory
        DeleteCategory: !GetAtt ProductsModule.Outputs.DeleteCategory
    DependsOn: Cognito

  LayerLibsPython:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer-lib-python
      Description: Librerías para funciones lambda de Python.
      ContentUri: src/shared/libs/.
      CompatibleRuntimes:
        - python3.9