AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Base para nuevas aplicaciones AWS SaaS

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: nodejs16.x
  Api:
    TracingEnabled: True

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml

  SettingsModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/settings/template.yaml
    DependsOn: Cognito

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-gateway/template.yaml
      Parameters:
        # COGNITO ARN
        CognitoUserPool: !GetAtt Cognito.Outputs.UserPoolARN
        # TEST FUNCTION
        PruebaFunction: !GetAtt SettingsModule.Outputs.PruebaFunction
    DependsOn: Cognito