AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Base para nuevas aplicaciones AWS SaaS

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: nodejs16.x
  Api:
    TracingEnabled: True

Resources:
  SettingsModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/settings/template.yaml

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-gateway/template.yaml
      Parameters:
        CreateTenant: !GetAtt SettingsModule.Outputs.CreateTenant