AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de la aplicación de transportes


Parameters:
  LayerLibsPython:
    Type: String
    Description: Referencia a las librerias para python


Globals:
  Function:
    Timeout: 60
    Runtime: python3.9
    Environment:
      Variables:
        CATEGORIES_TABLE: !Ref Categories
        AWS_ENV: "PROD"


Resources:
  GetCategories:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./get-categories
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Categories
      Layers:
        - !Ref LayerLibsPython

  CreateCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./create-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Categories
      Layers:
        - !Ref LayerLibsPython

  ReadCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./read-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Categories
      Layers:
        - !Ref LayerLibsPython

  UpdateCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./update-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Categories
      Layers:
        - !Ref LayerLibsPython

  DeleteCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./delete-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Categories
      Layers:
        - !Ref LayerLibsPython


  Categories:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BabyGift-Categories"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"


Outputs:
  GetCategories:
    Description: "GetCategories Lambda Function ARN"
    Value: !GetAtt GetCategories.Arn
  CreateCategory:
    Description: "CreateCategory Lambda Function ARN"
    Value: !GetAtt CreateCategory.Arn
  ReadCategory:
    Description: "ReadCategory Lambda Function ARN"
    Value: !GetAtt ReadCategory.Arn
  UpdateCategory:
    Description: "UpdateCategory Lambda Function ARN"
    Value: !GetAtt UpdateCategory.Arn
  DeleteCategory:
    Description: "DeleteCategory Lambda Function ARN"
    Value: !GetAtt DeleteCategory.Arn