AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de la aplicación de transportes

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs16.x

Resources:
  PruebaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: prueba.lambdaHandler
      # Layers:
      #   - !Ref libs
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PruebaTable
      Environment:
        Variables:
          PRUEBA_TABLE: !Ref PruebaTable


  PruebaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "PruebaTable"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"


Outputs:
  PruebaFunction:
    Description: "PruebaFunction Lambda Function ARN"
    Value: !GetAtt PruebaFunction.Arn