AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Recursos de cognito

  SAM Template para los recursos de cognito

Globals:
  Function:
    Timeout: 3

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AliasAttributes:
        - email
        - preferred_username
        - phone_number
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: transport-app
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH


  # UserPoolSSM:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type: String
  #     Name: /serverless-transport-app/cognito/user-pool-id
  #     Value: !Ref CognitoUserPool


  # UserPoolARNSSM:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type: String
  #     Name: /serverless-transport-app/cognito/user-pool-arn
  #     Value: !GetAtt CognitoUserPool.Arn


  # UserPoolAppClientSSM:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type: String
  #     Name: /serverless-transport-app/cognito/user-pool-client-id
  #     Value: !Ref UserPoolClient


Outputs:
  # CognitoUserPoolId:
  #   Description: "Cognito User Pool ID"
  #   Value: !Ref CognitoUserPool

  # CognitoAppClientId:
  #   Description: "Cognito App Client ID"
  #   Value: !Ref UserPoolClient

  # UserPoolARNSSM:
  #   Description: "UserPool ID"
  #   Value: !Ref UserPoolARNSSM

  UserPoolARN:
    Description: "UserPool ARN"
    Value: !GetAtt CognitoUserPool.Arn