AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Productos

  En este template se crean los EndPoints de Productos


Parameters:
  LayerLibsPython:
    Type: String
    Description: Referencia a las librerias para python


Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Layers:
      - !Ref LayerLibsPython
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable
        AWS_ENV: "PROD"


Resources:
  GetProducts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./get-products
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable

  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./create-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable

  ReadProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./read-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable

  UpdateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./update-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable

  DeleteProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./delete-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable


  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Products
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Name"
          AttributeType: "S"
        - AttributeName: "VirtualStore"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Name"
          KeyType: HASH
        - AttributeName: "VirtualStore"
          KeyType: RANGE


Outputs:
  GetProducts:
    Description: "GetProducts Lambda Function ARN"
    Value: !GetAtt GetProducts.Arn
  CreateProduct:
    Description: "CreateProduct Lambda Function ARN"
    Value: !GetAtt CreateProduct.Arn
  ReadProduct:
    Description: "ReadProduct Lambda Function ARN"
    Value: !GetAtt ReadProduct.Arn
  UpdateProduct:
    Description: "UpdateProduct Lambda Function ARN"
    Value: !GetAtt UpdateProduct.Arn
  DeleteProduct:
    Description: "DeleteProduct Lambda Function ARN"
    Value: !GetAtt DeleteProduct.Arn