AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Productos

  En este template se crean los EndPoints de Productos


Parameters:
  LayerLibsPython:
    Type: String
    Description: Referencia a las librerias para python

  MainStackName:
    Type: String
    Description: Nombre de la pila maestra

  MainTableBabyGift:
    Type: String
    Description: Referencia a la tabla maestra de BabyGift


Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Layers:
      - !Ref LayerLibsPython
    Environment:
      Variables:
        MAIN_TABLE_BABYGIFT: !Ref MainTableBabyGift
        AWS_ENV: "PROD"
        REGION: !Sub ${AWS::Region}


Resources:
  GetProducts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./get-products
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./create-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  ReadProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./read-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  UpdateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./update-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  DeleteProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./delete-product
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift


  # MainTableBabyGift:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub ${AWS::StackName}-Products
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: "Name"
  #         AttributeType: "S"
  #       - AttributeName: "VirtualStore"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "Name"
  #         KeyType: HASH
  #       - AttributeName: "VirtualStore"
          # KeyType: RANGE


Outputs:
  GetProducts:
    Description: "GetProducts Lambda Function ARN"
    Value: !GetAtt GetProducts.Arn
  CreateProduct:
    Description: "CreateProduct Lambda Function ARN"
    Value: !GetAtt CreateProduct.Arn
  ReadProduct:
    Description: "ReadProduct Lambda Function ARN"
    Value: !GetAtt ReadProduct.Arn
  UpdateProduct:
    Description: "UpdateProduct Lambda Function ARN"
    Value: !GetAtt UpdateProduct.Arn
  DeleteProduct:
    Description: "DeleteProduct Lambda Function ARN"
    Value: !GetAtt DeleteProduct.Arn