openapi: 3.0.1
info:
  title: babygift-admin
  version: '1.0'
servers:
  - url: /Prod
paths:
  /test-function:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        credentials:
          Fn::GetAtt:
            - ApiGwExecutionRole
            - Arn
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PruebaFunction}/invocations
        passthroughBehavior: when_no_match
components: {}
