AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de la aplicación de transportes

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs16.x

Resources:
  CreateTenant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: create-tenant.lambdaHandler
      # Layers:
      #   - !Ref libs
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
      Environment:
        Variables:
          TENANTS_TABLE: !Ref TenantsTable


  TenantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "TenantsTable"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
        - 
          AttributeName: "name"
          KeyType: "RANGE"

  # libs:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     LayerName: blank-nodejs-lib
  #     Description: Dependencies for the blank sample app.
  #     Content:
  #       S3Bucket: my-bucket-region-123456789012
  #       S3Key: layer.zip
  #     CompatibleRuntimes:
  #       - nodejs16.x   


Outputs:
  CreateTenant:
    Description: "CreateTenant Lambda Function ARN"
    Value: !GetAtt CreateTenant.Arn