AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de la aplicación de transportes

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs16.x

Resources:
  CreateTenant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: create-tenant.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
      Environment:
        Variables:
          TENANTS_TABLE: !Ref TenantsTable


  TenantsTable:
    Type: AWS::Serverless::SimpleTable


Outputs:
  CreateTenant:
    Description: "CreateTenant Lambda Function ARN"
    Value: !GetAtt CreateTenant.Arn