AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Categorías

  En este template se crean los EndPoints de categorías


Parameters:
  LayerLibsPython:
    Type: String
    Description: Referencia a las librerias para python

  LayerModelsPython:
    Type: String
    Description: Referencia a las modelos para python

  MainStackName:
    Type: String
    Description: Nombre de la pila maestra
  
  MainTableBabyGift:
    Type: String
    Description: Referencia a la tabla maestra de BabyGift


Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Layers:
      - !Ref LayerLibsPython
      - !Ref LayerModelsPython
    Environment:
      Variables:
        MAIN_TABLE_BABYGIFT: !Ref MainTableBabyGift
        AWS_ENV: "PROD"
        REGION: !Sub ${AWS::Region}


Resources:
  GetCategories:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./get-categories
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  CreateCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./create-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  ReadCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./read-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  UpdateCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./update-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift

  DeleteCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./delete-category
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTableBabyGift


Outputs:
  GetCategories:
    Description: "GetCategories Lambda Function ARN"
    Value: !GetAtt GetCategories.Arn
    Export:
      Name: !Sub ${MainStackName}-GetCategories
  CreateCategory:
    Description: "CreateCategory Lambda Function ARN"
    Value: !GetAtt CreateCategory.Arn
  ReadCategory:
    Description: "ReadCategory Lambda Function ARN"
    Value: !GetAtt ReadCategory.Arn
  UpdateCategory:
    Description: "UpdateCategory Lambda Function ARN"
    Value: !GetAtt UpdateCategory.Arn
  DeleteCategory:
    Description: "DeleteCategory Lambda Function ARN"
    Value: !GetAtt DeleteCategory.Arn