AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de tenant de la aplicación de transportes


Parameters:
  LayerLibsPython:
    Type: String
    Description: Referencia a las librerias para python


Globals:
  Function:
    Timeout: 5
    Runtime: nodejs16.x


Resources:
  CategoriesModule:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./categories/template.yaml
      Parameters:
        LayerLibsPython: !Ref LayerLibsPython


Outputs:
  GetCategories:
    Description: "GetCategories Lambda  ARN"
    Value: !GetAtt CategoriesModule.Outputs.GetCategories
  CreateCategory:
    Description: "CreateCategory Lambda  ARN"
    Value: !GetAtt CategoriesModule.Outputs.CreateCategory
  ReadCategory:
    Description: "ReadCategory Lambda  ARN"
    Value: !GetAtt CategoriesModule.Outputs.ReadCategory
  UpdateCategory:
    Description: "UpdateCategory Lambda  ARN"
    Value: !GetAtt CategoriesModule.Outputs.UpdateCategory
  DeleteCategory:
    Description: "DeleteCategory Lambda  ARN"
    Value: !GetAtt CategoriesModule.Outputs.DeleteCategory
  LayerLibsPython:
    Description: "Salida de referencia librerias python"
    Value: !Ref LayerLibsPython